echo "We are trying this practical from linux EC2"
echo "We are from batch-33 and learning git/gihub"
echo "We are learning Branching"
echo "I am learning Git & Git-Hub"
echo "I am learning all Devops tools and will get a job on this very soon"
echo "Hi Good Mornning, I have covered ansible and Docker recently"
